import AppKit
import Combine
import SwiftUI

/// Una cosa copiata.
struct VoceAppunti: Identifiable, Equatable {
    enum Contenuto: Equatable {
        case testo(String)
        case immagine(URL)      // materializzata su disco: vedi Archivio
        case file([URL])
    }

    let id: UUID
    let contenuto: Contenuto
    /// Il campione che dice se due immagini sono la stessa, senza rileggerle.
    /// `nil` per testo e file, che si confrontano direttamente.
    var impronta: String? = nil
    /// Chi l'ha messa negli appunti. `nil` quando il sistema non lo dice: mai
    /// un nome inventato (regola del default che nomina un attore).
    let app: String?
    let quando: Date
    /// Il testo letto dentro l'immagine, quando ce n'è (vedi `Ocr`).
    var testoLetto: String? = nil

    /// La riga che si legge sulla scheda.
    var titolo: String {
        switch contenuto {
        case .testo(let t):
            let pulito = t.trimmingCharacters(in: .whitespacesAndNewlines)
            return pulito.isEmpty ? " " : pulito
        case .immagine:
            return ""
        case .file(let urls):
            return urls.count == 1
                ? urls[0].lastPathComponent
                : "\(urls.count) file"
        }
    }

    /// Due voci sono la stessa cosa se il contenuto coincide. Serve a non
    /// impilare venti copie identiche quando premi ⌘C due volte.
    func stessoContenuto(di altra: VoceAppunti) -> Bool {
        switch (contenuto, altra.contenuto) {
        case (.testo(let a), .testo(let b)): a == b
        case (.file(let a), .file(let b)): a == b
        // Due immagini si confrontano sull'IMPRONTA, non sui byte e non sul
        // percorso. Il percorso è nostro e cambia a ogni cattura, quindi
        // direbbe «diversa» a ogni schermata identica; i byte sono giusti ma
        // vogliono due letture da otto megabyte a ogni copia, sul thread che
        // disegna. L'impronta si calcola una volta, quando l'immagine entra.
        case (.immagine, .immagine):
            impronta != nil && impronta == altra.impronta
        default: false
        }
    }
}

/// Il guardiano degli appunti.
///
/// NSPasteboard non notifica: si guarda `changeCount`, che è un contatore che
/// il sistema incrementa a ogni scrittura di chiunque. Mezzo secondo è il
/// passo che usano tutti (Maccy compreso) e sta sotto la soglia in cui
/// l'occhio si accorge del ritardo.
///
/// La risorsa qui è un timer, non l'audio o la fotocamera: tenerlo vivo per
/// tutta la vita del processo È l'uso (MacAppRules §0.3 chiede il contrario
/// solo per le risorse che il sistema può riconfigurare sotto di te).
@MainActor
final class Appunti: ObservableObject {
    @Published private(set) var voci: [VoceAppunti] = []

    /// Quante copie tenere. Oltre, le più vecchie escono da sole.
    var tetto: Int = 100 {
        didSet { pota() }
    }

    private let pasteboard = NSPasteboard.general
    private var ultimoConteggio: Int
    private var timer: Timer?
    private let archivio = Archivio(cartella: "appunti")

    /// I tipi che NON si registrano mai. `org.nspasteboard.ConcealedType` è la
    /// convenzione con cui i gestori di password dicono «questa copia è un
    /// segreto»: 1Password, Bitwarden e altri la scrivono. Registrarla
    /// vorrebbe dire tenere una password in chiaro sul disco per un'ora.
    private static let daNonRegistrare: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init() {
        ultimoConteggio = pasteboard.changeCount
        voci = archivio.rileggiAppunti()
    }

    /// Il seme della sonda visiva: voci decise dal banco, disco mai toccato.
    /// Senza questa porta la sonda fotograferebbe gli appunti VERI, cioè
    /// scriverebbe su disco quello che lui aveva copiato quel giorno.
    init(perSonda voci: [VoceAppunti]) {
        ultimoConteggio = 0
        self.voci = voci
    }

    func avvia() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.guarda() }
        }
        // `.common`: senza, il timer si ferma mentre tieni premuto un menu o
        // trascini una finestra, cioè esattamente quando stai copiando.
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func ferma() {
        timer?.invalidate()
        timer = nil
    }

    /// Rimette una voce negli appunti di sistema. La scrittura incrementa
    /// `changeCount`, quindi si allinea il contatore per non ri-registrare
    /// come nuova una cosa che c'era già.
    func riporta(_ voce: VoceAppunti) {
        pasteboard.clearContents()
        switch voce.contenuto {
        case .testo(let t):
            pasteboard.setString(t, forType: .string)
        case .immagine(let url):
            if let immagine = NSImage(contentsOf: url) {
                pasteboard.writeObjects([immagine])
            }
        case .file(let urls):
            pasteboard.writeObjects(urls as [NSURL])
        }
        ultimoConteggio = pasteboard.changeCount
        // Torna in cima: quello che riusi adesso è quello che riuserai ancora.
        if let indice = voci.firstIndex(where: { $0.id == voce.id }) {
            let v = voci.remove(at: indice)
            voci.insert(v, at: 0)
            archivio.scriviAppunti(voci)
        }
    }

    func dimentica(_ voce: VoceAppunti) {
        voci.removeAll { $0.id == voce.id }
        if case .immagine(let url) = voce.contenuto {
            try? FileManager.default.removeItem(at: url)
        }
        archivio.scriviAppunti(voci)
    }

    func svuota() {
        for voce in voci {
            if case .immagine(let url) = voce.contenuto {
                try? FileManager.default.removeItem(at: url)
            }
        }
        voci.removeAll()
        archivio.scriviAppunti(voci)
    }

    // MARK: - Il giro di guardia

    private func guarda() {
        let conteggio = pasteboard.changeCount
        guard conteggio != ultimoConteggio else { return }
        ultimoConteggio = conteggio
        // Il thread principale legge SOLO byte e stringhe: nessuna decodifica,
        // nessuna scrittura. Quello che costa va di là.
        guard let grezzo = leggiGrezzo() else { return }
        switch grezzo {
        case .pronta(let voce):
            aggiungi(voce)
        case .immagine(let dati, let giaPng, let app, let quando):
            let archivio = self.archivio
            Task.detached(priority: .utility) {
                let png = giaPng ? dati : Self.convertiInPng(dati)
                guard let png, let url = archivio.scriviByte(png, estensione: "png") else { return }
                let impronta = Archivio.impronta(png)
                await MainActor.run {
                    self.aggiungi(VoceAppunti(id: UUID(), contenuto: .immagine(url),
                                              impronta: impronta, app: app, quando: quando))
                }
            }
        }
    }

    /// Cosa c'era negli appunti, in una forma che il thread principale può
    /// produrre senza pagare niente.
    private enum Grezzo {
        case pronta(VoceAppunti)
        case immagine(dati: Data, giaPng: Bool, app: String?, quando: Date)
    }

    nonisolated private static func convertiInPng(_ dati: Data) -> Data? {
        NSBitmapImageRep(data: dati)?.representation(using: .png, properties: [:])
    }

    /// Legge quello che c'è adesso negli appunti. L'ordine conta: i file prima
    /// dell'immagine, perché copiando un PNG dal Finder il sistema offre
    /// ENTRAMBE le forme, e il file è quello che porta anche il nome.
    private func leggiGrezzo() -> Grezzo? {
        guard let tipi = pasteboard.types else { return nil }
        for segreto in Self.daNonRegistrare where tipi.contains(segreto) { return nil }

        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        let adesso = Date()

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            return .pronta(VoceAppunti(id: UUID(), contenuto: .file(urls), app: app, quando: adesso))
        }

        // I BYTE, non un `NSImage`. Una schermata è già PNG negli appunti:
        // presa così, scriverla costa mezzo millisecondo invece di 589.
        if let png = pasteboard.data(forType: .png) {
            return .immagine(dati: png, giaPng: true, app: app, quando: adesso)
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return .immagine(dati: tiff, giaPng: false, app: app, quando: adesso)
        }

        if let testo = pasteboard.string(forType: .string),
           !testo.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .pronta(VoceAppunti(id: UUID(), contenuto: .testo(testo), app: app, quando: adesso))
        }

        return nil
    }

    private func aggiungi(_ voce: VoceAppunti) {
        // Se è identica alla prima, non è una voce nuova: è la stessa cosa
        // ricopiata. Si aggiorna l'ora e basta.
        if let prima = voci.first, prima.stessoContenuto(di: voce) {
            if case .immagine(let url) = voce.contenuto {
                try? FileManager.default.removeItem(at: url)
            }
            return
        }
        // Se sta più in basso, risale in cima e non si duplica.
        if let indice = voci.firstIndex(where: { $0.stessoContenuto(di: voce) }) {
            let vecchia = voci.remove(at: indice)
            voci.insert(vecchia, at: 0)
            if case .immagine(let url) = voce.contenuto {
                try? FileManager.default.removeItem(at: url)
            }
            archivio.scriviAppunti(voci)
            return
        }
        voci.insert(voce, at: 0)
        pota()
        archivio.scriviAppunti(voci)
        if case .immagine(let url) = voce.contenuto { leggiIlTesto(id: voce.id, url: url) }
    }

    /// Il testo dentro un'immagine copiata, letto in sottofondo appena entra:
    /// così quando ti serve è già lì (vedi `Ocr` per il perché non c'è un
    /// comando «fai l'OCR»).
    private func leggiIlTesto(id: UUID, url: URL) {
        guard Ocr.attivo else { return }
        Task.detached(priority: .utility) {
            guard let testo = Ocr.testo(in: url) else { return }
            await MainActor.run { self.annota(id: id, testo: testo) }
        }
    }

    private func annota(id: UUID, testo: String) {
        guard let indice = voci.firstIndex(where: { $0.id == id }) else { return }
        voci[indice].testoLetto = testo
        archivio.scriviAppunti(voci)
    }

    private func pota() {
        guard voci.count > tetto else { return }
        let tagliate = voci[tetto...]
        for voce in tagliate {
            if case .immagine(let url) = voce.contenuto {
                try? FileManager.default.removeItem(at: url)
            }
        }
        voci = Array(voci.prefix(tetto))
    }
}
